### ISSUE TITLE
TODO Documentation

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/towards-a-new-website#17]
- [ ] Complete `README.md` with
  - [ ] How to add a post (detailed explanation of md header, esp. how do categories work)
  - [ ] What elements to use for custom pages
  - [ ] How to add to or modify the navigation bar

- [ ] Add a CONTRIBUTION.md with detailed information for developers

**Comment by hmoldenhauer** [comment]
Is important for me and other non-programmers to fill in some content

**Comment by bixel** [comment]
Looks like we need some kind of archive (see #20) for all posts. The category "special" will only show the 4 latest posts on the home page.

**Comment by Vanessa-Mueller** [comment]
Things to add to a "How to a post":
- [ ] how to add internal link 
- [ ] how to add external link
- [ ] how to add images 
- [ ] how to add a link to file

**Comment by bixel** [comment]
We also need to add installation instructions

**Comment by ccauet** [comment]
Would be great to provide some infos how to offline test the website

**Comment by bixel** [comment]
If you're on mac, [the README](https://github.com/pep-dortmund/homepage#testing) should explain it.

**Comment by bixel** [comment]
@MaxNoe looking at the TODO, I feel like most of the points should either be moved inside the CONTRIBUTION.md or into specific "developer" wiki pages (altough the single CONTRIBUTION.md file should be enough so far). What do you think? I would just keep the "Testing" section in the README.md to get people starting quickly.

**Comment by MaxNoe** [comment]
@bixel agreed

**Comment by hmoldenhauer** [comment]
The 'Testing' region has to be a bit more descriptive...
I installed everything as described, but when i run '''gem install bundler''' there's a warning
'''you don't have /home/... in your PATH, gem executables will not run'''
i had to add it to the PATH in my bashrc:
'''PATH="/home/.../.gem/.ruby/.2.4.0/bin:$PATH"

Maybe this came due to updating?

**Comment by hmoldenhauer** [comment]
There should also be a note that one has to be in the folder of the homepage...

**Comment by MaxNoe** [comment]
> The 'Testing' region has to be a bit more descriptive...
> I installed everything as described, but when i run '''gem install bundler''' there's a warning
> `''you don't have /home/... in your PATH, gem executables will not run''`
> i had to add it to the PATH in my bashrc:
> `export PATH="/home/.../.gem/.ruby/.2.4.0/bin:$PATH"`
> Maybe this came due to updating?

So you ran a command, it did not work but told you *exactly what to do*. Why should we document that here?

**Comment by MaxNoe** [comment]
Also, the README tells you to do
````
$ sudo gem install bundler
```
This should not do anything with your home and work right away. Did you do that?

**Comment by hmoldenhauer** [comment]
jep, did everything as requested.

Is working now. Errors that tell you what to to are friendly errors.

There should only be a note that you shouldn't try doing everything in your home directory, but you need to go to .../homepage/

**Comment by MaxNoe** [comment]
```
sudo gem instal bundler
```
should not put anything into your `$HOME`, but install everything systemwide to `/usr/bin` similiar

**Comment by hmoldenhauer** [comment]
for sure, but to run
```
bundle exec jekyll serve
```
you should be in path/to/homepage ;)

**Comment by MaxNoe** [comment]
Yes, I know. That's independent.

**Comment by hmoldenhauer** [comment]
it is not on my machine...
But it works, when in the given folder.

We should check it later or ignore it ;)

**Comment by MaxNoe** [comment]
That you have to be in the homepage folder to build the homepage should be pretty obvious

**Comment by hmoldenhauer** [comment]
yes, but a note should be added anyway

**Comment by MaxNoe** [comment]
I added it to the README
