### ISSUE TITLE
Design TODO

### ISSUE THREAD

**Issue by mennthor** [pep-dortmund/towards-a-new-website#8]
- [ ] Add Xing button in footer
- [ ] Darker grey for navigation bar
- [ ] Finalize content texts on static pages
- [ ] Finalize static page box design

**Comment by bixel** [comment]
Is this still a thing?

**Comment by MaxNoe** [comment]
I suppose so
